### ISSUE TITLE
Insert link working incorrectly

### ISSUE THREAD

**Issue by BenRussert** [lee-dohm/markdown-helper#2]
I get consistently incorrect results as seen in this gif.
![markdown-issue](https://cloud.githubusercontent.com/assets/10860657/25068522/f2b5c3ee-222b-11e7-9ce9-e4130e7618f3.gif)

**Comment by lee-dohm** [comment]
That's behaving exactly as described in the README:

> Opens a dialog asking for a title and a target. The title is the text that will be linked from and the target is the URL that will be linked to. When confirmed, it will insert a **reference link** at the current cursor position and add the reference at the end of the file.

See the documentation on [reference links](https://daringfireball.net/projects/markdown/syntax#link).

**Comment by BenRussert** [comment]
Ohhh, I see thanks!
